const projects = [
  {
    project_id: "Project01",
    name: "Introduction",
    project_pic: "/Project01.png",
    course: "beginner",
    subscription: 0,
    activity_type: "animation",
    year_level: 2,
    subject_matter: "science",
  },
  {
    project_id: "Project02",
    name: "My Birthday",
    project_pic: "/Project02.png",
    course: "advanced",
    subscription: 0,
    activity_type: "animation",
    year_level: 3,
    subject_matter: "maths",
  },

  {
    project_id: "Project03",
    name: "10 Block Challenge",
    project_pic: "/Project03.png",
    course: "beginner",
    subscription: 0,
    activity_type: "animation",
    year_level: 4,
    subject_matter: "art",
  },
  {
    project_id: "Project04",
    name: "Build a band",
    project_pic: "/Project04.png",
    course: "beginner",
    subscription: 0,
    activity_type: "game",
    year_level: 5,
    subject_matter: "music",
  },
  {
    project_id: "Project05",
    name: "name",
    project_pic: "/Project05.png",
    course: "beginner",
    subscription: 0,
    activity_type: "game",
    year_level: 2,
    subject_matter: "maths",
  },
  {
    project_id: "Project06",
    name: "name",
    project_pic: "/Project06.png",
    course: "beginner",
    subscription: 1,
    activity_type: "animation",
    year_level: 2,
    subject_matter: "maths",
  },
  {
    project_id: "Project07",
    name: "name",
    project_pic: "/Project07.png",
    course: "beginner",
    subscription: 0,
    activity_type: "animation",
    year_level: 8,
    subject_matter: "computer science",
  },
  {
    project_id: "Project08",
    name: "name",
    project_pic: "/Project08.png",
    course: "beginner",
    subscription: 1,
    activity_type: "chatbot",
    year_level: 2,
    subject_matter: "maths",
  },
  {
    project_id: "Project09",
    name: "name",
    project_pic: "/Project09.png",
    course: "beginner",
    subscription: 1,
    activity_type: "augmented reality",
    year_level: 2,
    subject_matter: "maths",
  },
  {
    project_id: "Project10",
    name: "name",
    project_pic: "/Project10.png",
    course: "beginner",
    subscription: 0,
    activity_type: "animation",
    year_level: 2,
    subject_matter: "science",
  },
  {
    project_id: "Project11",
    name: "name",
    project_pic: "/Project11.png",
    course: "beginner",
    subscription: 1,
    activity_type: "animation",
    year_level: 2,
    subject_matter: "maths",
  },
  {
    project_id: "Project12",
    name: "name",
    project_pic: "/Project12.png",
    course: "beginner",
    subscription: 0,
    activity_type: "animation",
    year_level: 2,
    subject_matter: "maths",
  },
  {
    project_id: "Project13",
    name: "name",
    project_pic: "/Project13.png",
    course: "beginner",
    subscription: 1,
    activity_type: "animation",
    year_level: 2,
    subject_matter: "maths",
  },
  {
    project_id: "Project14",
    name: "name",
    project_pic: "/Project14.png",
    course: "beginner",
    subscription: 0,
    activity_type: "animation",
    year_level: 2,
    subject_matter: "maths",
  },
  {
    project_id: "Project15",
    name: "name",
    project_pic: "/Project15.png",
    course: "beginner",
    subscription: 1,
    activity_type: "animation",
    year_level: 2,
    subject_matter: "maths",
  },
];

const filters = {
  course: ["beginner", "intermediate", "advanced"],
  subscription: ["free", "premium"],
  activity_type: ["animation", "game", "chatbot", "augmented reality"],
  year_level: ["1-4", "5-6", "7-8", "9-13"],
  subject_matter: [
    "computer science",
    "maths",
    "science",
    "language",
    "art",
    "music",
  ],
};

export { projects };
export { filters };
